name: Build Agro Mitra APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and release APK
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter clean
      - run: flutter pub get
      - run: flutter gen-l10n

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > /tmp/signup.jks

      - name: Set up keystore environment variables
        run: |
          echo "KEYSTORE_PATH=/tmp/signup.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - run: flutter build apk --release --split-per-abi

      - name: Generate dynamic tag
        run: echo "TAG=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG }}
          artifacts: 'build/app/outputs/apk/release/*'
          token: ${{ secrets.AGRO_MITRA_KEY }}
